### ISSUE TITLE
Move Collapse/Expand button

### ISSUE THREAD

**Issue by Taijk-nl** [soundjester/lemmy_monkey#25] opened 2023-06-25 06:36 UTC
Might I suggest request a modification if this is possible with your script:
`Move Collapse/Expand button to the front in a consistent location.`

Currently the Expand/Collapse button is behind the username and constantly moves location based on the names length.

This is what I suggest: (_Screenshot made on old.reddit.com with RES enabled_)
![image](https://github.com/soundjester/lemmy_monkey/assets/20067015/6c53280a-62a0-4da4-b5f4-b653344e15b6)

**Comment by soundjester** [comment] 2023-06-25 11:55
what version of the script are you using?  The current script (v2.2) already does this for Lemmy v0.18.

If your instance is still on v0.17.4, then you'll need to use https://github.com/soundjester/lemmy_monkey/blob/dev-v1.11-Lemmy-v0.17/old.reddit.compact.user.js:

![image](https://github.com/soundjester/lemmy_monkey/assets/11245779/6975b1ce-af15-4299-9bd4-2436c2445d24)

**Comment by Taijk-nl** [comment] 2023-06-25 14:22
First of all, Awsome that you had already though of this!! 

Then to the issue at hand:

- Script V 2.2 (source: GreasyFork)
- Using Firefox: 114.0.2

![image](https://github.com/soundjester/lemmy_monkey/assets/20067015/a929579f-667c-4983-8a6f-d2a8f542f0ec)

**Just tested it on**: 

- BeeHaw > Button behind username
- Lemmy.World > Button behind username
- Lemmy.ml > Button at the front (as your screenshot)
- sh.itjust.works > Button at the front (as your screenshot)
- Feddit.nl > Button behind username

_As far as I'm able to tell, all these run 0.18 looking at the new URL format._

i'd be open to sharing more info if this would help pin down the issue, let me know if you want me to jump on discord or anything.

**Comment by soundjester** [comment] 2023-06-25 14:40
beehaw, lemmy.world and feddit.nl are all still on v0.17.4.  You can tell by scrolling all the way to the bottom of the page and looking for BE: v.0.17.4 or BE: v0.18.

There will be some inconsistent experiences if you are browsing directly instead of through your home instance.  If your home instance is still on v.0.17.4 you'll need the previously linked version of the script.

**Comment by Taijk-nl** [comment] 2023-06-25 14:41
Thanks! sorry for the waste of time.

**Comment by soundjester** [comment] 2023-06-25 14:42
I don't mind.  This just highlights the difficulties of federation and the diverging paths caused by differing upgrade schedules/paths.

I'm going to close this as resolved, but come back or open a new issue if you find anything else.

**Closed as completed by soundjester** 2023-06-25 14:42 UTC

**Comment by Taijk-nl** [comment] 2023-06-25 14:58
ill also keep an eye on the instance version from now on.
ill wait for the instances to upgrade instead of running parallel scripts or downgrading.
